export const COLORS = {
  bg: "#111111",
  card: "#1e1e1e",
  text: "#e5e5e5",
  textMuted: "#a3a3a3",
  primary: "#7c3aed", // Obsidian Purple-ish
  primaryHover: "#6d28d9",
  danger: "#ef4444",
  border: "#333333",
  success: "#22c55e",
};

export const STYLES = {
  container: {
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
    backgroundColor: COLORS.bg,
    color: COLORS.text,
    height: "100dvh", // Use dynamic viewport height
    width: "100%",
    display: "flex",
    flexDirection: "column" as const,
    padding: "0",
    overflow: "hidden",
    boxSizing: "border-box" as const,
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "max(16px, env(safe-area-inset-top)) 20px 16px 20px",
    borderBottom: `1px solid ${COLORS.border}`,
    backgroundColor: COLORS.card,
  },
  title: {
    fontSize: "1.25rem",
    fontWeight: "700",
    margin: 0,
    background: "linear-gradient(to right, #c084fc, #7c3aed)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  editorArea: {
    flex: 1,
    display: "flex",
    flexDirection: "column" as const,
    padding: "16px",
    position: "relative" as const,
    overflow: "hidden",
  },
  textarea: {
    width: "100%",
    flex: 1,
    backgroundColor: "transparent",
    border: "none",
    color: COLORS.text,
    fontSize: "1.1rem",
    lineHeight: "1.6",
    resize: "none" as const,
    outline: "none",
    fontFamily: "inherit",
    padding: "0",
  },
  toolbar: {
    padding: "12px 16px calc(12px + env(safe-area-inset-bottom)) 16px",
    backgroundColor: COLORS.card,
    borderTop: `1px solid ${COLORS.border}`,
    display: "flex",
    gap: "10px",
    justifyContent: "space-between",
    alignItems: "center",
    minHeight: "70px",
  },
  button: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    padding: "12px 16px",
    borderRadius: "12px",
    border: "none",
    fontSize: "1rem",
    fontWeight: "600",
    cursor: "pointer",
    transition: "transform 0.1s ease, opacity 0.2s",
  },
  actionBtn: {
    backgroundColor: COLORS.card,
    color: COLORS.text,
    border: `1px solid ${COLORS.border}`,
  },
  primaryBtn: {
    backgroundColor: COLORS.primary,
    color: "#fff",
    flex: 2, // Make Send button larger
  },
  secondaryBtn: {
     backgroundColor: COLORS.card,
     color: COLORS.text,
     border: `1px solid ${COLORS.border}`,
     flex: 1,
  },
  iconBtn: {
    background: "transparent",
    border: "none",
    color: COLORS.text,
    cursor: "pointer",
    padding: "8px",
  },
  modalOverlay: {
    position: "fixed" as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.7)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 50,
    backdropFilter: "blur(4px)",
  },
  modal: {
    backgroundColor: COLORS.card,
    borderRadius: "16px",
    padding: "24px",
    width: "90%",
    maxWidth: "400px",
    maxHeight: "85vh",
    overflowY: "auto" as const,
    border: `1px solid ${COLORS.border}`,
    boxShadow: "0 20px 25px -5px rgba(0, 0, 0, 0.5)",
  },
  inputGroup: {
    marginBottom: "16px",
  },
  label: {
    display: "block",
    marginBottom: "8px",
    fontSize: "0.9rem",
    color: COLORS.textMuted,
  },
  input: {
    width: "100%",
    padding: "12px",
    borderRadius: "8px",
    backgroundColor: COLORS.bg,
    border: `1px solid ${COLORS.border}`,
    color: COLORS.text,
    fontSize: "1rem",
    outline: "none",
    boxSizing: "border-box" as const,
  },
  settingsTextarea: {
    width: "100%",
    padding: "12px",
    borderRadius: "8px",
    backgroundColor: COLORS.bg,
    border: `1px solid ${COLORS.border}`,
    color: COLORS.text,
    fontSize: "0.9rem",
    fontFamily: "monospace",
    minHeight: "100px",
    resize: "vertical" as const,
    outline: "none",
    boxSizing: "border-box" as const,
  },
  recordingIndicator: {
    position: "absolute" as const,
    top: "20px",
    right: "20px",
    backgroundColor: COLORS.danger,
    color: "white",
    padding: "6px 12px",
    borderRadius: "20px",
    fontSize: "0.8rem",
    fontWeight: "bold",
    display: "flex",
    alignItems: "center",
    gap: "6px",
    animation: "pulse 1.5s infinite",
  },
};